# CMake generated Testfile for 
# Source directory: G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test
# Build directory: G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sample_cache "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_sample_cache.exe")
  set_tests_properties(test_sample_cache PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;10;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sample_cache "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_sample_cache.exe")
  set_tests_properties(test_sample_cache PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;10;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sample_cache "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_sample_cache.exe")
  set_tests_properties(test_sample_cache PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;10;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sample_cache "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_sample_cache.exe")
  set_tests_properties(test_sample_cache PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;10;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_sample_cache NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sfont_loading "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_sfont_loading.exe")
  set_tests_properties(test_sfont_loading PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;11;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sfont_loading "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_sfont_loading.exe")
  set_tests_properties(test_sfont_loading PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;11;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sfont_loading "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_sfont_loading.exe")
  set_tests_properties(test_sfont_loading PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;11;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sfont_loading "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_sfont_loading.exe")
  set_tests_properties(test_sfont_loading PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;11;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_sfont_loading NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sample_rate_change "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_sample_rate_change.exe")
  set_tests_properties(test_sample_rate_change PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;12;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sample_rate_change "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_sample_rate_change.exe")
  set_tests_properties(test_sample_rate_change PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;12;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sample_rate_change "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_sample_rate_change.exe")
  set_tests_properties(test_sample_rate_change PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;12;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sample_rate_change "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_sample_rate_change.exe")
  set_tests_properties(test_sample_rate_change PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;12;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_sample_rate_change NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_pointer_alignment "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_pointer_alignment.exe")
  set_tests_properties(test_pointer_alignment PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;14;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_pointer_alignment "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_pointer_alignment.exe")
  set_tests_properties(test_pointer_alignment PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;14;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_pointer_alignment "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_pointer_alignment.exe")
  set_tests_properties(test_pointer_alignment PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;14;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_pointer_alignment "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_pointer_alignment.exe")
  set_tests_properties(test_pointer_alignment PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;14;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_pointer_alignment NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_seqbind_unregister "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_seqbind_unregister.exe")
  set_tests_properties(test_seqbind_unregister PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;15;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_seqbind_unregister "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_seqbind_unregister.exe")
  set_tests_properties(test_seqbind_unregister PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;15;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_seqbind_unregister "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_seqbind_unregister.exe")
  set_tests_properties(test_seqbind_unregister PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;15;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_seqbind_unregister "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_seqbind_unregister.exe")
  set_tests_properties(test_seqbind_unregister PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;15;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_seqbind_unregister NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_synth_chorus_reverb "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_synth_chorus_reverb.exe")
  set_tests_properties(test_synth_chorus_reverb PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;16;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_synth_chorus_reverb "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_synth_chorus_reverb.exe")
  set_tests_properties(test_synth_chorus_reverb PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;16;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_synth_chorus_reverb "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_synth_chorus_reverb.exe")
  set_tests_properties(test_synth_chorus_reverb PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;16;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_synth_chorus_reverb "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_synth_chorus_reverb.exe")
  set_tests_properties(test_synth_chorus_reverb PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;16;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_synth_chorus_reverb NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_snprintf "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_snprintf.exe")
  set_tests_properties(test_snprintf PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;17;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_snprintf "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_snprintf.exe")
  set_tests_properties(test_snprintf PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;17;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_snprintf "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_snprintf.exe")
  set_tests_properties(test_snprintf PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;17;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_snprintf "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_snprintf.exe")
  set_tests_properties(test_snprintf PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;17;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_snprintf NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_synth_process "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Debug/test_synth_process.exe")
  set_tests_properties(test_synth_process PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;18;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_synth_process "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/Release/test_synth_process.exe")
  set_tests_properties(test_synth_process PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;18;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_synth_process "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/MinSizeRel/test_synth_process.exe")
  set_tests_properties(test_synth_process PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;18;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_synth_process "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/RelWithDebInfo/test_synth_process.exe")
  set_tests_properties(test_synth_process PROPERTIES  _BACKTRACE_TRIPLES "G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;18;ADD_FLUID_TEST;G:/1.devproject/kumyoung-karaoke-clone/work/FluidSynth/fluidsynth-2.0.6/test/CMakeLists.txt;0;")
else()
  add_test(test_synth_process NOT_AVAILABLE)
endif()
